name: Build Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pyramid-converter-dl-2-hipims
    - name: test
      run: docker run -v "$(pwd)/data:/data" pyramid-converter-dl-2-hipims
