name: Upload to DAFNI

on:
  release:
    types: [published]
    
  workflow_dispatch:

jobs:
  release:
    name: Upload to DAFNI
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Docker Build
        run: docker build -t pyramid-fod-2-hipims:latest .

      - name: Compress docker image
        run: docker save pyramid-fod-2-hipims:latest | gzip > pyramid-fod-2-hipims.tar.gz

      - name: Set tag as env
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Upload to DAFNI
        uses: dafnifacility/dafni-model-uploader@v1.9
        with:
          definition-path: './model-definition.yml'
          image-path: './pyramid-fod-2-hipims.tar.gz'
          username: ${{ secrets.DAFNI_SERVICE_ACCOUNT_USERNAME }}
          password: ${{ secrets.DAFNI_SERVICE_ACCOUNT_PASSWORD }}
          version-message: ${{ env.TAG }}
          parent-model: "c834816c-eb82-4f07-96aa-72f13020afa4"
